baseURL = 'https://raymonhardy.github.io'
languageCode = 'en-us'
title = "Ray's Blog"
theme = 'hugo-PaperMod'

[params.homeInfoParams]
Title = "Posts"
# Content = "Cyber Security Blog"

[[params.socialIcons]]
name = "Github"
url = "https://github.com/raymonhardy"

[[params.socialIcons]]
name = "linkedIn"
url = "https://www.linkedin.com/in/raymonhardy/"